Comment out work for now

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,39 +27,39 @@ jobs:
 
     - uses: actions/checkout@v3
 
-    - uses: ruby/setup-ruby@v1
-      with:
-        ruby-version: .ruby-version
-        bundler-cache: true
+    # - uses: ruby/setup-ruby@v1
+    #   with:
+    #     ruby-version: .ruby-version
+    #     bundler-cache: true
 
-    - name: Cache Mint
-      id: cache-mint
-      uses: actions/cache@v3
-      with:
-        path: ~/.mint
-        key: ${{ runner.os }}-mint-v1-${{ hashFiles('Mintfile') }}
+    # - name: Cache Mint
+    #   id: cache-mint
+    #   uses: actions/cache@v3
+    #   with:
+    #     path: ~/.mint
+    #     key: ${{ runner.os }}-mint-v1-${{ hashFiles('Mintfile') }}
 
-    - name: Bootstrap
-      env:
-        HOMEBREW_NO_AUTO_UPDATE: 1
-        HOMEBREW_NO_INSTALL_CLEANUP: 1
-      run: |
-        make setup # NOTE: - CI won't run bundle install
-        make tools
+    # - name: Bootstrap
+    #   env:
+    #     HOMEBREW_NO_AUTO_UPDATE: 1
+    #     HOMEBREW_NO_INSTALL_CLEANUP: 1
+    #   run: |
+    #     make setup # NOTE: - CI won't run bundle install
+    #     make tools
 
-    - name: Codegen
-      run: |
-        make codegen
-        if [[ ! -z $(git status --porcelain | grep -Ev 'Brewfile.lock.json|Gemfile.lock') ]]; then
-          echo 'Codegen produced uncommitted changes. Commit changes and re-push.'
-          exit 1
-        fi
+    # - name: Codegen
+    #   run: |
+    #     make codegen
+    #     if [[ ! -z $(git status --porcelain | grep -Ev 'Brewfile.lock.json|Gemfile.lock') ]]; then
+    #       echo 'Codegen produced uncommitted changes. Commit changes and re-push.'
+    #       exit 1
+    #     fi
 
-    - name: Lint
-      run: make lint
+    # - name: Lint
+    #   run: make lint
 
-    - name: Test
-      run: make test-${{ matrix.test-os }}
+    # - name: Test
+    #   run: make test-${{ matrix.test-os }}
 
     - name: Coverage
       if: matrix.test-os == 'macos'
